/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.app.poo.vista.cliente;

import ec.edu.ups.app.poo.controlador.ClienteControlador;
import ec.edu.ups.app.poo.modelo.Cliente;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class VentanaEditarCliente extends javax.swing.JInternalFrame {
     private ClienteControlador clienteControlador;
    /**
     * Creates new form VentanaEditarCliente
     */
    public VentanaEditarCliente(ClienteControlador clienteControlador) {
        initComponents();
        this.clienteControlador = clienteControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbNombreCliente = new javax.swing.JLabel();
        lbIdentificiacionCliente = new javax.swing.JLabel();
        lbCorreoCliente = new javax.swing.JLabel();
        btEditarCliente = new javax.swing.JButton();
        txtIdentificacionCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtCorreoCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        bnLimpiar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Editar Cliente");

        jPanel1.setBackground(new java.awt.Color(160, 177, 132));
        jPanel1.setToolTipText("");

        lbNombreCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNombreCliente.setText("Nombre");

        lbIdentificiacionCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbIdentificiacionCliente.setText("Identificación");

        lbCorreoCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCorreoCliente.setText("Correo");

        btEditarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        btEditarCliente.setText(" Editar");
        btEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarClienteActionPerformed(evt);
            }
        });

        txtNombreCliente.setEditable(false);
        txtNombreCliente.setBackground(new java.awt.Color(70, 73, 75));
        txtNombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        txtCorreoCliente.setEditable(false);
        txtCorreoCliente.setBackground(new java.awt.Color(70, 73, 75));
        txtCorreoCliente.setForeground(new java.awt.Color(255, 255, 255));

        btnBuscarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda-2.png"))); // NOI18N
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        bnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/escoba.png"))); // NOI18N
        bnLimpiar.setText("Limpiar");
        bnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbIdentificiacionCliente)
                            .addComponent(lbNombreCliente)
                            .addComponent(lbCorreoCliente))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdentificacionCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(txtNombreCliente))
                                .addGap(29, 29, 29)
                                .addComponent(btnBuscarCliente))
                            .addComponent(txtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(btEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(bnLimpiar)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdentificiacionCliente)
                    .addComponent(txtIdentificacionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreCliente)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCorreoCliente)
                    .addComponent(txtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditarCliente)
                    .addComponent(bnLimpiar))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void btEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarClienteActionPerformed
        // TODO add your handling code here:
        String identificacion = txtIdentificacionCliente.getText();
        String nombre = txtNombreCliente.getText();
        String correo = txtCorreoCliente.getText();
        
        clienteControlador.update(nombre, identificacion, correo);
        JOptionPane.showMessageDialog(this, "Se actualizo correctamente!");
        limpiarDatos();
            
        
        
    }//GEN-LAST:event_btEditarClienteActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        String identificacion = txtIdentificacionCliente.getText();
        Cliente cliente = clienteControlador.read(identificacion);
        if (cliente==null){
            JOptionPane.showMessageDialog(this, "El cliente no existe!");
        }else{
            txtIdentificacionCliente.setEditable(false);
            txtIdentificacionCliente.setText(cliente.getIdentificacion());
            txtNombreCliente.setText(cliente.getNombre());
            txtNombreCliente.setEditable(true);
            txtCorreoCliente.setText(cliente.getCorreo());
            txtCorreoCliente.setEditable(true);

        }
    }
    private void limpiarDatos(){
        txtIdentificacionCliente.setEditable(true);
            txtIdentificacionCliente.setText("");
            txtNombreCliente.setText("");
            txtNombreCliente.setEditable(false);
            txtCorreoCliente.setText("");
            txtCorreoCliente.setEditable(false);
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void bnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarDatos();
    }//GEN-LAST:event_bnLimpiarActionPerformed

    public void cambiarIdioma(Locale locale) {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
        ResourceBundle titulos = ResourceBundle.getBundle("titulos.titulos", locale); 
            this.setTitle(titulos.getString("EditarC"));
        lbIdentificiacionCliente.setText(mensajes.getString("idCliente"));
        lbNombreCliente.setText(mensajes.getString("nombre"));
        lbCorreoCliente.setText(mensajes.getString("correoCliente"));
        btnBuscarCliente.setText(mensajes.getString("buscarBibliotecaMenu"));      
        btEditarCliente.setText(mensajes.getString("botonEditar"));
        bnLimpiar.setText(mensajes.getString("botonLimpiar"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnLimpiar;
    private javax.swing.JButton btEditarCliente;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCorreoCliente;
    private javax.swing.JLabel lbIdentificiacionCliente;
    private javax.swing.JLabel lbNombreCliente;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JTextField txtIdentificacionCliente;
    private javax.swing.JTextField txtNombreCliente;
    // End of variables declaration//GEN-END:variables
}
