/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.app.poo.vista.cliente;
    

import ec.edu.ups.app.poo.controlador.ClienteControlador;
import ec.edu.ups.app.poo.controlador.ClienteControlador;
import ec.edu.ups.app.poo.modelo.Cliente;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class VentanaEliminarCliente extends javax.swing.JInternalFrame {
    private ClienteControlador clienteControlador;
    /**
     * Creates new form VentanaEliminarCliente
     */
    public VentanaEliminarCliente(ClienteControlador clienteControlador) {
        initComponents();
        this.clienteControlador = clienteControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        codigoEliminar = new javax.swing.JLabel();
        txtIdentificacionEliminar = new javax.swing.JTextField();
        btnEliminarIdentificacion = new javax.swing.JButton();
        lbNombreCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        lbCorreoCliente = new javax.swing.JLabel();
        txtCorreoCliente = new javax.swing.JTextField();
        bnLimpiar = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Eliminar Cliente");

        jPanel1.setBackground(new java.awt.Color(171, 123, 123));

        codigoEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        codigoEliminar.setText("Identificación");

        txtIdentificacionEliminar.setBackground(new java.awt.Color(143, 119, 65));

        btnEliminarIdentificacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarIdentificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btnEliminarIdentificacion.setText("Eliminar");
        btnEliminarIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarIdentificacionActionPerformed(evt);
            }
        });

        lbNombreCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNombreCliente.setText("Nombre");

        txtNombreCliente.setEditable(false);
        txtNombreCliente.setBackground(new java.awt.Color(143, 119, 65));
        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        lbCorreoCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCorreoCliente.setText("Correo");

        txtCorreoCliente.setEditable(false);
        txtCorreoCliente.setBackground(new java.awt.Color(143, 119, 65));

        bnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/escoba.png"))); // NOI18N
        bnLimpiar.setText("Limpiar");
        bnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnLimpiarActionPerformed(evt);
            }
        });

        btnBuscarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda-2.png"))); // NOI18N
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNombreCliente)
                    .addComponent(lbCorreoCliente))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIdentificacionEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnBuscarCliente))
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEliminarIdentificacion)
                .addGap(67, 67, 67)
                .addComponent(bnLimpiar)
                .addGap(163, 163, 163))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdentificacionEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoEliminar)
                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNombreCliente))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCorreoCliente)
                    .addComponent(txtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnLimpiar)
                    .addComponent(btnEliminarIdentificacion))
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarIdentificacionActionPerformed
        // TODO add your handling code here:
        String identificacion = txtIdentificacionEliminar.getText();
        int respuesta = JOptionPane.showConfirmDialog(this, "Estas seguro de eliminar el Cliente");
        if(respuesta== JOptionPane.YES_OPTION){
        clienteControlador.delete(identificacion);
        JOptionPane.showMessageDialog(this, "Se ha eliminado correctamente!");
        limpiarDatos();
        }
         
    }//GEN-LAST:event_btnEliminarIdentificacionActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void bnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarDatos();
    }//GEN-LAST:event_bnLimpiarActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        String identificacion = txtIdentificacionEliminar.getText();
        Cliente cliente = clienteControlador.read(identificacion);
        if (cliente==null){
            JOptionPane.showMessageDialog(this, "El cliente no existe!");
        }else{
            txtIdentificacionEliminar.setEditable(false);
            txtIdentificacionEliminar.setText(cliente.getIdentificacion());
            txtNombreCliente.setText(cliente.getNombre());
            txtNombreCliente.setEditable(true);
            txtCorreoCliente.setText(cliente.getCorreo());
            txtCorreoCliente.setEditable(true);

        }
        }
        private void limpiarDatos(){
            txtIdentificacionEliminar.setEditable(true);
            txtIdentificacionEliminar.setText("");
            txtNombreCliente.setText("");
            txtNombreCliente.setEditable(false);
            txtCorreoCliente.setText("");
            txtCorreoCliente.setEditable(false);
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

        public void cambiarIdioma(Locale locale) {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
        ResourceBundle titulos = ResourceBundle.getBundle("titulos.titulos", locale); 
            this.setTitle(titulos.getString("EliminarC"));
        codigoEliminar.setText(mensajes.getString("idCliente"));
        lbNombreCliente.setText(mensajes.getString("nombre"));
        lbCorreoCliente.setText(mensajes.getString("correoCliente"));
        btnBuscarCliente.setText(mensajes.getString("buscarBibliotecaMenu"));      
        btnEliminarIdentificacion.setText(mensajes.getString("eliminarBiblioteca"));
        bnLimpiar.setText(mensajes.getString("botonLimpiar"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnLimpiar;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnEliminarIdentificacion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel codigoEliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCorreoCliente;
    private javax.swing.JLabel lbNombreCliente;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JTextField txtIdentificacionEliminar;
    private javax.swing.JTextField txtNombreCliente;
    // End of variables declaration//GEN-END:variables
}
