/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.app.poo.vista.cliente;

import ec.edu.ups.app.poo.controlador.ClienteControlador;
import ec.edu.ups.app.poo.modelo.Cliente;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class VentanaListarClientes extends javax.swing.JInternalFrame {
     private ClienteControlador clienteControlador;
     
    /**
     * Creates new form VentanaListarClientes
     */
    public VentanaListarClientes(ClienteControlador clienteControlador) {
        initComponents();
        this.clienteControlador = clienteControlador;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2ListarCliente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListarCliente = new javax.swing.JTable();
        btListarCliente = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Listar Clientes");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel2ListarCliente.setBackground(new java.awt.Color(123, 171, 156));
        jPanel2ListarCliente.setToolTipText("");

        tbListarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Identificación", "Nombre", "Correo"
            }
        ));
        jScrollPane1.setViewportView(tbListarCliente);

        btListarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btListarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lista.png"))); // NOI18N
        btListarCliente.setText("Listar");
        btListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2ListarClienteLayout = new javax.swing.GroupLayout(jPanel2ListarCliente);
        jPanel2ListarCliente.setLayout(jPanel2ListarClienteLayout);
        jPanel2ListarClienteLayout.setHorizontalGroup(
            jPanel2ListarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2ListarClienteLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel2ListarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btListarCliente)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel2ListarClienteLayout.setVerticalGroup(
            jPanel2ListarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2ListarClienteLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btListarCliente)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2ListarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2ListarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarClienteActionPerformed
        // TODO add your handling code here:
        cargarDatos();
        
    }
    public void cargarDatos(){
        List<Cliente> clientes = clienteControlador.list();
        DefaultTableModel tabla =  (DefaultTableModel) tbListarCliente.getModel();
        tabla.setNumRows(0);
        for(Cliente cliente : clientes){
            Object[] rowData = {cliente.getIdentificacion(),cliente.getNombre(),cliente.getCorreo()};
            tabla.addRow(rowData);
            
        }
    }//GEN-LAST:event_btListarClienteActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        cargarDatos();
    }//GEN-LAST:event_formInternalFrameActivated

    public void cambiarIdioma(Locale locale) {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
        ResourceBundle titulos = ResourceBundle.getBundle("titulos.titulos", locale);
        ResourceBundle tablas = ResourceBundle.getBundle("tablas.tablas", locale); 
        String indentificacion = tablas.getString( "tablaIdentificacion");
        String nombre = tablas.getString("tablaNombre");
        String correo = tablas.getString("tablaCorreo");
        DefaultTableModel tabla = (DefaultTableModel) tbListarCliente.getModel();
        tabla.setColumnIdentifiers(new String [] {indentificacion,nombre,correo});
            this.setTitle(titulos.getString("ListarC"));
        btListarCliente.setText(mensajes.getString("listarBiblioteca"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btListarCliente;
    private javax.swing.JPanel jPanel2ListarCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbListarCliente;
    // End of variables declaration//GEN-END:variables
}
