/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.app.poo.vista.biblioteca;

import ec.edu.ups.app.poo.controlador.BibliotecaControlador;
import ec.edu.ups.app.poo.modelo.Biblioteca;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class VentanaEditarBiblioteca extends javax.swing.JInternalFrame {
    private BibliotecaControlador bibliotecaControlador;
    /**
     * Creates new form VentanaEditarBiblioteca
     */
    public VentanaEditarBiblioteca(BibliotecaControlador bibliotecaControlador) {
        initComponents();
        this.bibliotecaControlador = bibliotecaControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        nombreBiblioteca2Actualizar = new javax.swing.JLabel();
        direccionBiblioteca2Actualizar = new javax.swing.JLabel();
        codigoBiblioteca2Actualizar = new javax.swing.JLabel();
        telefonoBiblioteca2Actualizar = new javax.swing.JLabel();
        txtCodigo2Actualizar = new javax.swing.JTextField();
        txtNombre2Actualizar = new javax.swing.JTextField();
        txtDireccion2Actualizar = new javax.swing.JTextField();
        txtTelefonoActualizar = new javax.swing.JTextField();
        actualizarBiblioteca2 = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Editar Biblioteca");

        jPanel4.setBackground(new java.awt.Color(160, 177, 132));
        jPanel4.setToolTipText("");

        nombreBiblioteca2Actualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombreBiblioteca2Actualizar.setText("Nombre");

        direccionBiblioteca2Actualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        direccionBiblioteca2Actualizar.setText("Dirección");

        codigoBiblioteca2Actualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        codigoBiblioteca2Actualizar.setText("Codigo");

        telefonoBiblioteca2Actualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        telefonoBiblioteca2Actualizar.setText("Teléfono");

        txtCodigo2Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigo2ActualizarActionPerformed(evt);
            }
        });

        txtNombre2Actualizar.setEditable(false);
        txtNombre2Actualizar.setBackground(new java.awt.Color(70, 73, 75));
        txtNombre2Actualizar.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre2Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre2ActualizarActionPerformed(evt);
            }
        });

        txtDireccion2Actualizar.setEditable(false);
        txtDireccion2Actualizar.setBackground(new java.awt.Color(70, 73, 75));
        txtDireccion2Actualizar.setForeground(new java.awt.Color(255, 255, 255));

        txtTelefonoActualizar.setEditable(false);
        txtTelefonoActualizar.setBackground(new java.awt.Color(70, 73, 75));
        txtTelefonoActualizar.setForeground(new java.awt.Color(255, 255, 255));

        actualizarBiblioteca2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        actualizarBiblioteca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        actualizarBiblioteca2.setText("Editar");
        actualizarBiblioteca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarBiblioteca2ActionPerformed(evt);
            }
        });

        jbBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda-2.png"))); // NOI18N
        jbBuscar.setText(" Buscar");
        jbBuscar.setToolTipText("");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        btLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/escoba.png"))); // NOI18N
        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direccionBiblioteca2Actualizar)
                            .addComponent(telefonoBiblioteca2Actualizar)
                            .addComponent(nombreBiblioteca2Actualizar)
                            .addComponent(codigoBiblioteca2Actualizar))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelefonoActualizar)
                            .addComponent(txtCodigo2Actualizar)
                            .addComponent(txtNombre2Actualizar)
                            .addComponent(txtDireccion2Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(jbBuscar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(actualizarBiblioteca2)
                        .addGap(78, 78, 78)
                        .addComponent(btLimpiar)
                        .addGap(62, 62, 62)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo2Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoBiblioteca2Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre2Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreBiblioteca2Actualizar))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion2Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionBiblioteca2Actualizar))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoBiblioteca2Actualizar)
                    .addComponent(txtTelefonoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualizarBiblioteca2)
                    .addComponent(btLimpiar))
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigo2ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigo2ActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo2ActualizarActionPerformed

    private void txtNombre2ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre2ActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre2ActualizarActionPerformed

    private void actualizarBiblioteca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarBiblioteca2ActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(txtCodigo2Actualizar.getText());
        String nombre = txtNombre2Actualizar.getText();
        String direccion= txtDireccion2Actualizar.getText();
        String telefono = txtTelefonoActualizar.getText();
        
        bibliotecaControlador.update(codigo, nombre, direccion, telefono);
        JOptionPane.showMessageDialog(this, "Se ha actualizado correctamente!");
        
        limpiarDatos();
        
           
        
        
    }//GEN-LAST:event_actualizarBiblioteca2ActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(txtCodigo2Actualizar.getText());
        Biblioteca biblioteca = bibliotecaControlador.read(codigo);
        if(biblioteca!= null){
            txtDireccion2Actualizar.setText(biblioteca.getDireccion());
            txtNombre2Actualizar.setText(biblioteca.getNombre());
            txtTelefonoActualizar.setText(biblioteca.getTelefono());
            txtNombre2Actualizar.setEditable(true);
             txtDireccion2Actualizar.setEditable(true);
             txtTelefonoActualizar.setEditable(true);
            txtCodigo2Actualizar.setEditable(true);
        }else{
            JOptionPane.showMessageDialog(this, "No existe la biblioteca a editar");
        }
        
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        // TODO add your handling code here:
      limpiarDatos();
        
      
    }
    private void limpiarDatos(){
        txtCodigo2Actualizar.setEditable(true);
        txtNombre2Actualizar.setEditable(false);
        txtDireccion2Actualizar.setEditable(false);
        txtTelefonoActualizar.setEditable(false);
        txtCodigo2Actualizar.setText("");
        txtNombre2Actualizar.setText("");
        txtDireccion2Actualizar.setText("");
        txtTelefonoActualizar.setText("");
    }//GEN-LAST:event_btLimpiarActionPerformed
    public void cambiarIdioma(Locale locale) {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
        ResourceBundle titulos = ResourceBundle.getBundle("titulos.titulos", locale); 
            this.setTitle(titulos.getString("EditarB"));
        codigoBiblioteca2Actualizar.setText(mensajes.getString("codigo"));
        nombreBiblioteca2Actualizar.setText(mensajes.getString("nombre"));
        direccionBiblioteca2Actualizar.setText(mensajes.getString("direccion"));
        telefonoBiblioteca2Actualizar.setText(mensajes.getString("telefono"));
        jbBuscar.setText(mensajes.getString("botonBuscar"));
        actualizarBiblioteca2.setText(mensajes.getString("botonEditar"));
        btLimpiar.setText(mensajes.getString("botonLimpiar"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarBiblioteca2;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JLabel codigoBiblioteca2Actualizar;
    private javax.swing.JLabel direccionBiblioteca2Actualizar;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JLabel nombreBiblioteca2Actualizar;
    private javax.swing.JLabel telefonoBiblioteca2Actualizar;
    private javax.swing.JTextField txtCodigo2Actualizar;
    private javax.swing.JTextField txtDireccion2Actualizar;
    private javax.swing.JTextField txtNombre2Actualizar;
    private javax.swing.JTextField txtTelefonoActualizar;
    // End of variables declaration//GEN-END:variables
}
