/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.app.poo.vista.biblioteca;

import ec.edu.ups.app.poo.controlador.BibliotecaControlador;
import ec.edu.ups.app.poo.modelo.Biblioteca;
import ec.edu.ups.app.poo.modelo.Libro;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class VentanaBuscarBiblioteca extends javax.swing.JInternalFrame {
     private BibliotecaControlador bibliotecaControlador;
    

    @Override
    public void setMaximum(boolean b) throws PropertyVetoException {
        super.setMaximum(b); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void setMaximumSize(Dimension maximumSize) {
        super.setMaximumSize(maximumSize); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }


    public VentanaBuscarBiblioteca(BibliotecaControlador bibliotecaControlador, JButton btnBuscarB, JLabel codigoBuscar, JLabel direccionBiblioteca, JLabel jLabel1, JPanel jPanel1, JProgressBar jProgressBar1, JScrollPane jScrollPane2, JLabel lbLibrosPrestados1, JLabel nombreBibliotecaBuscar, JTable tbLibro, JLabel telefonoBiblioteca, JTextField txtCodigoBuscar, JTextField txtDireccion, JTextField txtNombre, JTextField txtTelefono) {
        this.bibliotecaControlador = bibliotecaControlador;
        this.btnBuscarB = btnBuscarB;
        this.codigoBuscar = codigoBuscar;
        this.direccionBiblioteca = direccionBiblioteca;
        this.jLabel1 = jLabel1;
        this.jPanel1 = jPanel1;
        this.jProgressBar1 = jProgressBar1;
        this.jScrollPane2 = jScrollPane2;
        this.lbLibrosPrestados1 = lbLibrosPrestados1;
        this.nombreBibliotecaBuscar = nombreBibliotecaBuscar;
        this.tbLibro = tbLibro;
        this.telefonoBiblioteca = telefonoBiblioteca;
        this.txtCodigoBuscar = txtCodigoBuscar;
        this.txtDireccion = txtDireccion;
        this.txtNombre = txtNombre;
        this.txtTelefono = txtTelefono;
    }
     
    /**
     * Creates new form VentanaBuscarBiblioteca
     */
    public VentanaBuscarBiblioteca(BibliotecaControlador bibliotecaControlador) {
        initComponents();
        this.bibliotecaControlador = bibliotecaControlador;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        codigoBuscar = new javax.swing.JLabel();
        txtCodigoBuscar = new javax.swing.JTextField();
        btnBuscarB = new javax.swing.JButton();
        nombreBibliotecaBuscar = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        direccionBiblioteca = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        telefonoBiblioteca = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbLibro = new javax.swing.JTable();
        lbLibrosPrestados1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Biblioteca"));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMaximumSize(new java.awt.Dimension(598, 467));
        setMinimumSize(new java.awt.Dimension(598, 467));
        setVisible(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(114, 135, 174));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("");
        jPanel1.setMaximumSize(new java.awt.Dimension(586, 442));
        jPanel1.setMinimumSize(new java.awt.Dimension(586, 442));

        codigoBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        codigoBuscar.setText("Codigo");

        txtCodigoBuscar.setToolTipText("");
        txtCodigoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoBuscarActionPerformed(evt);
            }
        });

        btnBuscarB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda-2.png"))); // NOI18N
        btnBuscarB.setText("  Buscar");
        btnBuscarB.setToolTipText("");
        btnBuscarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarBActionPerformed(evt);
            }
        });

        nombreBibliotecaBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombreBibliotecaBuscar.setText("Nombre");

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(70, 73, 75));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        direccionBiblioteca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        direccionBiblioteca.setText("Dirección");

        txtDireccion.setEditable(false);
        txtDireccion.setBackground(new java.awt.Color(70, 73, 75));
        txtDireccion.setForeground(new java.awt.Color(255, 255, 255));

        telefonoBiblioteca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        telefonoBiblioteca.setText("Teléfono");

        txtTelefono.setEditable(false);
        txtTelefono.setBackground(new java.awt.Color(70, 73, 75));
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        tbLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor", "Año", "Género", "Disponible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbLibro);

        lbLibrosPrestados1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbLibrosPrestados1.setText("Libros:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbLibrosPrestados1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreBibliotecaBuscar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(telefonoBiblioteca)
                        .addComponent(direccionBiblioteca))
                    .addComponent(codigoBuscar))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtNombre)
                            .addComponent(txtCodigoBuscar))
                        .addGap(38, 38, 38)
                        .addComponent(btnBuscarB))
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoBuscar)
                    .addComponent(btnBuscarB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreBibliotecaBuscar)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionBiblioteca)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoBiblioteca)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbLibrosPrestados1)
                        .addGap(99, 99, 99))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(1, 1, 608, 502);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCodigoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoBuscarActionPerformed

    private void btnBuscarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarBActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(txtCodigoBuscar.getText());
        Biblioteca biblioteca = bibliotecaControlador.read(codigo);
        if(biblioteca ==null){
            JOptionPane.showMessageDialog(this, "No se ha encontrado la bibioteca");
        }else{
            txtNombre.setText(biblioteca.getNombre());
            txtDireccion.setText(biblioteca.getDireccion());
            txtTelefono.setText(biblioteca.getTelefono());
            cargarDatos();
        }
    }//GEN-LAST:event_btnBuscarBActionPerformed

    
    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }
    private void cargarDatos() {
        Biblioteca biblioteca = bibliotecaControlador.read(Integer.parseInt(txtCodigoBuscar.getText()));
        List<Libro> libros = bibliotecaControlador.listLibros(biblioteca.getNombre());
        DefaultTableModel tabla = (DefaultTableModel) tbLibro.getModel();
        tabla.setNumRows(0);
        for (Libro libro : libros) {
            Object[] rowData = {libro.getTitulo(), libro.getAutor(), libro.getAño(), libro.getGenero(), libro.getDisponible()};
            tabla.addRow(rowData);
        }     
        
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized
    public void cambiarIdioma(Locale locale) {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
        ResourceBundle titulos = ResourceBundle.getBundle("titulos.titulos", locale); 
        ResourceBundle tablas = ResourceBundle.getBundle("tablas.tablas", locale); 
        String titulo = tablas.getString("tablaTitulo");
        String autor = tablas.getString("tablaAutor");
        String ano = tablas.getString("tablaAno");
        String genero = tablas.getString("tablaGenero");   
        String disponible = tablas.getString("tablaDisponible");               
        DefaultTableModel tabla = (DefaultTableModel) tbLibro.getModel();
        tabla.setColumnIdentifiers(new String [] {titulo, autor,ano,genero,disponible});
            this.setTitle(titulos.getString("BuscarB"));
        codigoBuscar.setText(mensajes.getString("codigo"));
        nombreBibliotecaBuscar.setText(mensajes.getString("nombre"));
        direccionBiblioteca.setText(mensajes.getString("direccion"));
        telefonoBiblioteca.setText(mensajes.getString("telefono"));
        btnBuscarB.setText(mensajes.getString("botonBuscar"));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarB;
    private javax.swing.JLabel codigoBuscar;
    private javax.swing.JLabel direccionBiblioteca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbLibrosPrestados1;
    private javax.swing.JLabel nombreBibliotecaBuscar;
    private javax.swing.JTable tbLibro;
    private javax.swing.JLabel telefonoBiblioteca;
    private javax.swing.JTextField txtCodigoBuscar;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
