/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.app.poo.vista.biblioteca;

import ec.edu.ups.app.poo.controlador.BibliotecaControlador;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class VentanaCrearBiblioteca extends javax.swing.JInternalFrame {
    private BibliotecaControlador bibliotecaControlador;
   
    /**
     * Creates new form VentanaCrearBilblioteca
     */
    public VentanaCrearBiblioteca(BibliotecaControlador bibliotecaControlador) {
        initComponents();
        
        this.bibliotecaControlador  = bibliotecaControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        nombreBiblioteca = new javax.swing.JLabel();
        direccionBiblioteca = new javax.swing.JLabel();
        codigoBiblioteca = new javax.swing.JLabel();
        telefonoBiblioteca = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        guardarBiblioteca = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setBackground(new java.awt.Color(163, 127, 83));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Crear nueva Biblioteca");
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(487, 389));
        setMinimumSize(new java.awt.Dimension(487, 389));

        jPanel1.setBackground(new java.awt.Color(195, 172, 133));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel1.setAutoscrolls(true);

        nombreBiblioteca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombreBiblioteca.setText("Nombre");

        direccionBiblioteca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        direccionBiblioteca.setText("Dirección");

        codigoBiblioteca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        codigoBiblioteca.setText("Codigo");

        telefonoBiblioteca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        telefonoBiblioteca.setText("Teléfono");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        guardarBiblioteca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        guardarBiblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        guardarBiblioteca.setText(" Guardar");
        guardarBiblioteca.setToolTipText("");
        guardarBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBibliotecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direccionBiblioteca)
                            .addComponent(telefonoBiblioteca)
                            .addComponent(nombreBiblioteca)
                            .addComponent(codigoBiblioteca))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(guardarBiblioteca)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreBiblioteca))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(direccionBiblioteca)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoBiblioteca)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(guardarBiblioteca)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 601, 501);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void guardarBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBibliotecaActionPerformed
        // TODO add your handling code here:}     
        int codigo = Integer.parseInt(txtCodigo.getText());
        
        String nombre = txtNombre.getText();
        String direccion = txtDireccion.getText();
        String telefono = txtTelefono.getText();
        if(bibliotecaControlador.read(codigo)== null){
        bibliotecaControlador.create(codigo, nombre, direccion, telefono);
        JOptionPane.showMessageDialog(this, "Biblioteca Creada exitosamente! :)");
        txtCodigo.setText("");
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        }else{   
            JOptionPane.showMessageDialog(this, "La biblioteca ya existe!");
        }
    }
        public void cambiarIdioma(Locale locale){
            ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
            ResourceBundle titulos = ResourceBundle.getBundle("titulos.titulos", locale); 
            this.setTitle(titulos.getString("CrearB"));
            codigoBiblioteca.setText(mensajes.getString("codigo"));
            nombreBiblioteca.setText(mensajes.getString("nombre"));
            direccionBiblioteca.setText(mensajes.getString("direccion"));
            telefonoBiblioteca.setText(mensajes.getString("telefono"));
            guardarBiblioteca.setText(mensajes.getString("botonCrear"));     
    }//GEN-LAST:event_guardarBibliotecaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codigoBiblioteca;
    private javax.swing.JLabel direccionBiblioteca;
    private javax.swing.JButton guardarBiblioteca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel nombreBiblioteca;
    private javax.swing.JLabel telefonoBiblioteca;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
