/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.app.poo.vista.biblioteca;

import ec.edu.ups.app.poo.controlador.BibliotecaControlador;
import ec.edu.ups.app.poo.modelo.Biblioteca;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class VentanaEliminarBiblioteca extends javax.swing.JInternalFrame {
     private BibliotecaControlador bibliotecaControlador;
     
    /**
     * Creates new form VentanaEliminarBiblioteca
     */
    public VentanaEliminarBiblioteca(BibliotecaControlador bibliotecaControlador) {
        initComponents();
         this.bibliotecaControlador = bibliotecaControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        codigoEliminar = new javax.swing.JLabel();
        txtCodigoEliminar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        nombreBibliotecaEliminar = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        direccionBibliotecaEliminar = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        telefonoBibliotecaEliminar = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        bnLimpiar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Eliminar Biblioteca"));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(171, 123, 123));

        codigoEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        codigoEliminar.setText("Codigo");

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        nombreBibliotecaEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombreBibliotecaEliminar.setText("Nombre");

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(70, 73, 75));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        direccionBibliotecaEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        direccionBibliotecaEliminar.setText("Dirección");

        txtDireccion.setEditable(false);
        txtDireccion.setBackground(new java.awt.Color(70, 73, 75));
        txtDireccion.setForeground(new java.awt.Color(255, 255, 255));

        telefonoBibliotecaEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        telefonoBibliotecaEliminar.setText("Teléfono");

        txtTelefono.setEditable(false);
        txtTelefono.setBackground(new java.awt.Color(70, 73, 75));
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));

        btBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda-2.png"))); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        bnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/escoba.png"))); // NOI18N
        bnLimpiar.setText("Limpiar");
        bnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addGap(73, 73, 73)
                        .addComponent(bnLimpiar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(direccionBibliotecaEliminar)
                                    .addComponent(telefonoBibliotecaEliminar)
                                    .addComponent(nombreBibliotecaEliminar))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtTelefono)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(codigoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(txtCodigoEliminar)))
                        .addGap(18, 18, 18)
                        .addComponent(btBuscar)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoEliminar)
                    .addComponent(txtCodigoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreBibliotecaEliminar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionBibliotecaEliminar))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoBibliotecaEliminar)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(bnLimpiar))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int respuesta=  JOptionPane.showConfirmDialog(this, "Estas seguro que deseas eliminar la Biblioteca");
        if(respuesta == JOptionPane.YES_OPTION){
        int codigo = Integer.parseInt(txtCodigoEliminar.getText());
        bibliotecaControlador.delete(codigo);
        JOptionPane.showMessageDialog(this, "Se ha eliminado correctamente!");
        limpiarDatos();
        }
        
            
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
       int codigo = Integer.parseInt(txtCodigoEliminar.getText());
       Biblioteca biblioteca = bibliotecaControlador.read(codigo);
       if(biblioteca != null){
           txtNombre.setText(biblioteca.getNombre());
           txtDireccion.setText(biblioteca.getDireccion());
           txtTelefono.setText(biblioteca.getTelefono());
           txtCodigoEliminar.setEditable(false);
       }else{
           JOptionPane.showMessageDialog(this, "La biblioteca no existe!");
       }
    }
       
    public void limpiarDatos(){
        txtCodigoEliminar.setText("");
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtCodigoEliminar.setEditable(true);
    
       
    }//GEN-LAST:event_btBuscarActionPerformed

    private void bnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarDatos();
    }//GEN-LAST:event_bnLimpiarActionPerformed
    public void cambiarIdioma(Locale locale) {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
        ResourceBundle titulos = ResourceBundle.getBundle("titulos.titulos", locale); 
            this.setTitle(titulos.getString("EliminarB"));
        codigoEliminar.setText(mensajes.getString("codigo"));
        direccionBibliotecaEliminar.setText(mensajes.getString("nombre"));
        direccionBibliotecaEliminar.setText(mensajes.getString("direccion"));
        telefonoBibliotecaEliminar.setText(mensajes.getString("telefono"));
        btBuscar.setText(mensajes.getString("botonBuscar"));
        btnEliminar.setText(mensajes.getString("eliminarBiblioteca"));
        bnLimpiar.setText(mensajes.getString("botonLimpiar"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnLimpiar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel codigoEliminar;
    private javax.swing.JLabel direccionBibliotecaEliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreBibliotecaEliminar;
    private javax.swing.JLabel telefonoBibliotecaEliminar;
    private javax.swing.JTextField txtCodigoEliminar;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
