/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.app.poo.vista.libro;

import ec.edu.ups.app.poo.controlador.LibroControlador;
import ec.edu.ups.app.poo.modelo.Libro;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class VentanaEliminarLibro extends javax.swing.JInternalFrame {
     private LibroControlador libroControlador;
    /**
     * Creates new form VentanaEliminarLibro
     */
    public VentanaEliminarLibro(LibroControlador libroControlador) {
        initComponents();
        this.libroControlador = libroControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btEliminarLibro = new javax.swing.JButton();
        lbTituloLibro = new javax.swing.JLabel();
        txtLibroTitulo = new javax.swing.JTextField();
        lbAutorLibro = new javax.swing.JLabel();
        txtLibroAutor = new javax.swing.JTextField();
        lbAñoLibro = new javax.swing.JLabel();
        txtLibroAño = new javax.swing.JTextField();
        generoLibro = new javax.swing.JLabel();
        txtLibroGenero = new javax.swing.JTextField();
        lbDisponibleLibro1 = new javax.swing.JLabel();
        txtLibroDisponibleBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lbCodigo1 = new javax.swing.JLabel();
        txtCodigo1 = new javax.swing.JTextField();

        lbCodigo.setText("Codigo");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Eliminar Libro");

        jPanel1.setBackground(new java.awt.Color(171, 123, 123));

        btEliminarLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btEliminarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btEliminarLibro.setText("Eliminar");
        btEliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarLibroActionPerformed(evt);
            }
        });

        lbTituloLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTituloLibro.setText("Titulo");

        txtLibroTitulo.setEditable(false);
        txtLibroTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibroTituloActionPerformed(evt);
            }
        });

        lbAutorLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAutorLibro.setText("Autor");

        txtLibroAutor.setEditable(false);
        txtLibroAutor.setBackground(new java.awt.Color(70, 73, 75));
        txtLibroAutor.setForeground(new java.awt.Color(255, 255, 255));

        lbAñoLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAñoLibro.setText("Año");

        txtLibroAño.setEditable(false);
        txtLibroAño.setBackground(new java.awt.Color(70, 73, 75));
        txtLibroAño.setForeground(new java.awt.Color(255, 255, 255));
        txtLibroAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibroAñoActionPerformed(evt);
            }
        });

        generoLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        generoLibro.setText("Género");

        txtLibroGenero.setEditable(false);
        txtLibroGenero.setBackground(new java.awt.Color(70, 73, 75));
        txtLibroGenero.setForeground(new java.awt.Color(255, 255, 255));

        lbDisponibleLibro1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDisponibleLibro1.setText("Disponible");

        txtLibroDisponibleBuscar.setEditable(false);
        txtLibroDisponibleBuscar.setBackground(new java.awt.Color(70, 73, 75));
        txtLibroDisponibleBuscar.setForeground(new java.awt.Color(255, 255, 255));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda-2.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/escoba.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lbCodigo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCodigo1.setText("Codigo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btEliminarLibro)
                        .addGap(60, 60, 60)
                        .addComponent(btnLimpiar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtLibroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbAñoLibro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtLibroAño, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(generoLibro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtLibroGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbDisponibleLibro1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                        .addComponent(txtLibroDisponibleBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbTituloLibro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtLibroTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lbCodigo1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addGap(95, 95, 95))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCodigo1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTituloLibro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLibroTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAutorLibro)
                    .addComponent(txtLibroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbAñoLibro)
                        .addGap(19, 19, 19))
                    .addComponent(txtLibroAño, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(generoLibro)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtLibroGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDisponibleLibro1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLibroDisponibleBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEliminarLibro)
                    .addComponent(btnLimpiar))
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarLibroActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(txtCodigo1.getText());
        int respuesta= JOptionPane.showConfirmDialog(this, "Esta seguro de eliminar el Libro");
        if(respuesta == JOptionPane.YES_OPTION){
            Libro libro = libroControlador.read(codigo);
        libroControlador.delete(codigo, libro.getNombiblioteca());
        JOptionPane.showMessageDialog(this, "Se ha eliminado correctamente!");
        limpiarDatos();
        }
            
        
    }//GEN-LAST:event_btEliminarLibroActionPerformed

    private void txtLibroTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibroTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibroTituloActionPerformed

    private void txtLibroAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibroAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibroAñoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(txtCodigo1.getText());
        Libro libro = libroControlador.read(codigo);
        if(libro!= null){
            txtLibroAutor.setText(libro.getAutor());
            txtLibroAño.setText(String.valueOf(libro.getAño()));
            txtLibroDisponibleBuscar.setText(String.valueOf(libro.getDisponible()));
            txtLibroGenero.setText(libro.getGenero());
            txtLibroTitulo.setText(libro.getTitulo());
            txtCodigo1.setEditable(false);

        }else{
            JOptionPane.showMessageDialog(this, "El libro a eliminar no existe!");
        }
        
    }
    public void limpiarDatos(){
        txtLibroTitulo.setText("");
        txtLibroAutor.setText("");
        txtLibroAño.setText("");
        txtLibroDisponibleBuscar.setText("");
        txtLibroGenero.setText("");
        txtCodigo1.setText("");
        txtCodigo1.setEditable(true);

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarDatos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    public void cambiarIdioma(Locale locale) {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
        ResourceBundle titulos = ResourceBundle.getBundle("titulos.titulos", locale); 
            this.setTitle(titulos.getString("EliminarL"));
        lbTituloLibro.setText(mensajes.getString("tituloLibro"));
        lbAutorLibro.setText(mensajes.getString("autorLibro"));
        lbAñoLibro.setText(mensajes.getString("anoLibro"));
        generoLibro.setText(mensajes.getString("Genero"));
        lbDisponibleLibro1.setText(mensajes.getString("disponibleLibro"));
        btnBuscar.setText(mensajes.getString("botonBuscar"));
        btEliminarLibro.setText(mensajes.getString("eliminarBiblioteca"));
        btnLimpiar.setText(mensajes.getString("botonLimpiar"));
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEliminarLibro;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel generoLibro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAutorLibro;
    private javax.swing.JLabel lbAñoLibro;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCodigo1;
    private javax.swing.JLabel lbDisponibleLibro1;
    private javax.swing.JLabel lbTituloLibro;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigo1;
    private javax.swing.JTextField txtLibroAutor;
    private javax.swing.JTextField txtLibroAño;
    private javax.swing.JTextField txtLibroDisponibleBuscar;
    private javax.swing.JTextField txtLibroGenero;
    private javax.swing.JTextField txtLibroTitulo;
    // End of variables declaration//GEN-END:variables
}
