/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.app.poo.vista.libro;

import ec.edu.ups.app.poo.DAO.BibliotecaDAO;
import ec.edu.ups.app.poo.IDAO.BibliotecaIDAO;
import ec.edu.ups.app.poo.controlador.BibliotecaControlador;
import ec.edu.ups.app.poo.controlador.LibroControlador;
import ec.edu.ups.app.poo.modelo.Biblioteca;
import ec.edu.ups.app.poo.modelo.Libro;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class VentanaCrearLibro extends javax.swing.JInternalFrame {
    
     private LibroControlador libroControlador;
     private BibliotecaControlador bibliotecaControlador;
     private BibliotecaIDAO bibliotecaDAO;
    /**
     * Creates new form VentanaCrearLibro
     */
    public VentanaCrearLibro(LibroControlador libroControlador, BibliotecaControlador bibliotecaControlador,BibliotecaIDAO bibliotecaDAO ) {
        initComponents();
        this.libroControlador = libroControlador;
        this.bibliotecaControlador = bibliotecaControlador;
        this.bibliotecaDAO = bibliotecaDAO;
        agregarAlCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbTituloLibro = new javax.swing.JLabel();
        lbAutorLibro = new javax.swing.JLabel();
        lbAñoLibro = new javax.swing.JLabel();
        txtLibroTitulo = new javax.swing.JTextField();
        txtLibroAutor = new javax.swing.JTextField();
        txtLibroAño = new javax.swing.JTextField();
        txtGuardarLibro = new javax.swing.JButton();
        generoLibro = new javax.swing.JLabel();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        bibliotecaBox = new javax.swing.JComboBox<>();
        lbCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setBorder(javax.swing.BorderFactory.createTitledBorder("Crear Libro"));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(195, 172, 133));
        jPanel1.setToolTipText("");

        lbTituloLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTituloLibro.setText("Titulo");

        lbAutorLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAutorLibro.setText("Autor");

        lbAñoLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAñoLibro.setText("Año");

        txtLibroTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibroTituloActionPerformed(evt);
            }
        });

        txtLibroAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibroAñoActionPerformed(evt);
            }
        });

        txtGuardarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        txtGuardarLibro.setText(" Guardar");
        txtGuardarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuardarLibroActionPerformed(evt);
            }
        });

        generoLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        generoLibro.setText("Género");

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comedia", "Romance", "Ficción", "Misterio", "Terror" }));
        jComboBoxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGeneroActionPerformed(evt);
            }
        });

        bibliotecaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bibliotecaBoxActionPerformed(evt);
            }
        });

        lbCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCodigo.setText("Codigo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTituloLibro)
                                    .addComponent(lbAñoLibro)
                                    .addComponent(generoLibro)
                                    .addComponent(lbCodigo)
                                    .addComponent(lbAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtLibroAutor)
                                        .addComponent(txtLibroAño)
                                        .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCodigo)
                                            .addComponent(txtLibroTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                                        .addGap(73, 73, 73)
                                        .addComponent(bibliotecaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(txtGuardarLibro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bibliotecaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLibroTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTituloLibro))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAutorLibro)
                    .addComponent(txtLibroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbAñoLibro)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(generoLibro)
                            .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtLibroAño, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(txtGuardarLibro)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        agregarAlCombo();
    }//GEN-LAST:event_formInternalFrameActivated

    private void bibliotecaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bibliotecaBoxActionPerformed
        // TODO add your handling code here:

        }
        public void agregarAlCombo(){
            bibliotecaBox.removeAllItems();
            List<Biblioteca> bibliotecas = bibliotecaControlador.list();
            for (Biblioteca biblioteca : bibliotecas) {
                bibliotecaBox.addItem(biblioteca.getNombre());
            }
    }//GEN-LAST:event_bibliotecaBoxActionPerformed

    private void jComboBoxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGeneroActionPerformed

    private void txtGuardarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuardarLibroActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(txtCodigo.getText());
        String titulo = txtLibroTitulo.getText();
        String autor = txtLibroAutor.getText();
        int año = Integer.parseInt(txtLibroAño.getText());
        String genero = (String) jComboBoxGenero.getSelectedItem();
        String nomBiblioteca = String.valueOf(bibliotecaBox.getSelectedItem());

        // Código para recuperar información y crear el libro
        if(libroControlador.read(codigo)== null){
            libroControlador.create(codigo, titulo, autor, año, genero, "SI",nomBiblioteca );
            Libro libro = libroControlador.read(codigo);
            libro.setNombiblioteca(String.valueOf(bibliotecaBox.getSelectedItem()));
            Biblioteca biblioteca = bibliotecaControlador.read(nomBiblioteca);
            if(biblioteca!= null){
            biblioteca.agregarLibros(libro);
            bibliotecaControlador.agregarLibro(nomBiblioteca, libro);
            }else{
                System.out.println("La biblioteca no existe!");
            }
            
            JOptionPane.showMessageDialog(this, "Se ha creado exitosamente");
            agregarAlCombo();
            // Limpiar campos de texto

        }else{
            JOptionPane.showMessageDialog(this, "El libro ya existe!");
        }
        txtLibroTitulo.setText("");
        txtLibroAutor.setText("");
        txtLibroAño.setText("");
        txtCodigo.setText("");
    }//GEN-LAST:event_txtGuardarLibroActionPerformed

    private void txtLibroAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibroAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibroAñoActionPerformed

    private void txtLibroTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibroTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibroTituloActionPerformed

    public void cambiarIdioma(Locale locale) {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
        ResourceBundle titulos = ResourceBundle.getBundle("titulos.titulos", locale); 
            this.setTitle(titulos.getString("CrearL"));
        lbTituloLibro.setText(mensajes.getString("tituloLibro"));
        lbAutorLibro.setText(mensajes.getString("autorLibro"));
        lbAñoLibro.setText(mensajes.getString("anoLibro"));
        generoLibro.setText(mensajes.getString("Genero"));
        txtGuardarLibro.setText(mensajes.getString("crearBibliotecaMenu"));
        lbCodigo.setText(mensajes.getString("codigo"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bibliotecaBox;
    private javax.swing.JLabel generoLibro;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAutorLibro;
    private javax.swing.JLabel lbAñoLibro;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbTituloLibro;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JButton txtGuardarLibro;
    private javax.swing.JTextField txtLibroAutor;
    private javax.swing.JTextField txtLibroAño;
    private javax.swing.JTextField txtLibroTitulo;
    // End of variables declaration//GEN-END:variables
}
