/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.app.poo.vista.libro;

import ec.edu.ups.app.poo.controlador.LibroControlador;
import ec.edu.ups.app.poo.modelo.Libro;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class VentanaEditarLibro extends javax.swing.JInternalFrame {
     private LibroControlador libroControlador;
    /**
     * Creates new form VentanaEditarLibro
     */
    public VentanaEditarLibro(LibroControlador libroControlador) {
        initComponents();
        this.libroControlador = libroControlador;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbTituloLibro = new javax.swing.JLabel();
        lbAutorLibro = new javax.swing.JLabel();
        lbAñoLibro = new javax.swing.JLabel();
        lbGenero = new javax.swing.JLabel();
        txtTituloEditar = new javax.swing.JTextField();
        txtAutorEditar = new javax.swing.JTextField();
        txtAñoEditar = new javax.swing.JTextField();
        txtEditarLibro = new javax.swing.JButton();
        lbDisponibleLibro1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        disponibleBOX = new javax.swing.JComboBox<>();
        txtCodigo = new javax.swing.JTextField();
        lbCodigo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Editar Libro");

        jPanel2.setBackground(new java.awt.Color(160, 177, 132));
        jPanel2.setToolTipText("");

        lbTituloLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTituloLibro.setText("Titulo");

        lbAutorLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAutorLibro.setText("Autor");

        lbAñoLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAñoLibro.setText("Año");

        lbGenero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbGenero.setText("Género");

        txtTituloEditar.setEditable(false);
        txtTituloEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloEditarActionPerformed(evt);
            }
        });

        txtAutorEditar.setEditable(false);
        txtAutorEditar.setBackground(new java.awt.Color(70, 73, 75));
        txtAutorEditar.setForeground(new java.awt.Color(255, 255, 255));

        txtAñoEditar.setEditable(false);
        txtAñoEditar.setBackground(new java.awt.Color(70, 73, 75));
        txtAñoEditar.setForeground(new java.awt.Color(255, 255, 255));

        txtEditarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        txtEditarLibro.setText("Editar");
        txtEditarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditarLibroActionPerformed(evt);
            }
        });

        lbDisponibleLibro1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDisponibleLibro1.setText("Disponible");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda-2.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jbLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/escoba.png"))); // NOI18N
        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comedia", "Romance", "Ficción", "Misterio", "Terror" }));
        jComboBoxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGeneroActionPerformed(evt);
            }
        });

        disponibleBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));

        lbCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCodigo.setText("Codigo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addGap(98, 98, 98))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(94, 94, 94)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtEditarLibro)
                                .addGap(61, 61, 61)
                                .addComponent(jbLimpiar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTituloLibro)
                                    .addComponent(lbAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbAñoLibro)
                                    .addComponent(lbGenero)
                                    .addComponent(lbDisponibleLibro1)
                                    .addComponent(lbCodigo))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTituloEditar)
                                    .addComponent(txtAutorEditar)
                                    .addComponent(txtAñoEditar)
                                    .addComponent(jComboBoxGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(disponibleBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap(153, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTituloLibro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTituloEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAutorEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAutorLibro))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAñoLibro)
                    .addComponent(txtAñoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGenero)
                    .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDisponibleLibro1)
                            .addComponent(disponibleBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(173, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEditarLibro)
                            .addComponent(jbLimpiar))
                        .addGap(82, 82, 82))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloEditarActionPerformed

    private void txtEditarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditarLibroActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(txtCodigo.getText());
        Libro libro = libroControlador.read(codigo);
        String titulo = txtTituloEditar.getText();
        String autor = txtAutorEditar.getText();
        int año = Integer.parseInt(txtAñoEditar.getText());
        String genero = (String)jComboBoxGenero.getSelectedItem();
        String disponible = (String)disponibleBOX.getSelectedItem();
        libroControlador.update(codigo, titulo, autor, año, genero, disponible,libro.getNombiblioteca());
        JOptionPane.showMessageDialog(this, "Se actualizo correctamente!");
        limpiarDatos();
       
    }//GEN-LAST:event_txtEditarLibroActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
       int codigo = Integer.parseInt(txtCodigo.getText());
        Libro libro = libroControlador.read(codigo);
        if(libro!= null){
            txtTituloEditar.setText(libro.getTitulo());
            txtAutorEditar.setText(libro.getAutor());
            txtAñoEditar.setText(String.valueOf(libro.getAño()));
            disponibleBOX.setSelectedItem(String.valueOf(libro.getDisponible()));
            jComboBoxGenero.setSelectedItem(libro.getGenero());
            txtAutorEditar.setEditable(true);
            txtAñoEditar.setEditable(true);
            disponibleBOX.setEditable(true);
            jComboBoxGenero.setEditable(true);
            txtTituloEditar.setEditable(true);
            txtCodigo.setEditable(false);
            
        }else{
            JOptionPane.showMessageDialog(this, "El libro a editar no existe!");
        }
     
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarDatos();
    }
    private void limpiarDatos(){
        txtAutorEditar.setEditable(false);
        txtAñoEditar.setEditable(false);
        disponibleBOX.setEditable(false);
        jComboBoxGenero.setEditable(false);
        txtTituloEditar.setEditable(false);
        txtCodigo.setEditable(true);
        txtAutorEditar.setText("");
        txtAñoEditar.setText("");
        txtTituloEditar.setText("");
        txtCodigo.setText("");
        
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jComboBoxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGeneroActionPerformed

    public void cambiarIdioma(Locale locale) {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
        ResourceBundle titulos = ResourceBundle.getBundle("titulos.titulos", locale); 
            this.setTitle(titulos.getString("EditarL"));
        lbTituloLibro.setText(mensajes.getString("tituloLibro"));
        lbAutorLibro.setText(mensajes.getString("autorLibro"));
        lbAñoLibro.setText(mensajes.getString("anoLibro"));
        lbGenero.setText(mensajes.getString("Genero"));
        lbDisponibleLibro1.setText(mensajes.getString("disponibleLibro"));
        btnBuscar.setText(mensajes.getString("botonBuscar"));
        txtEditarLibro.setText(mensajes.getString("botonEditar"));
        jbLimpiar.setText(mensajes.getString("botonLimpiar"));
         lbCodigo.setText(mensajes.getString("codigo"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> disponibleBOX;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JLabel lbAutorLibro;
    private javax.swing.JLabel lbAñoLibro;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbDisponibleLibro1;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbTituloLibro;
    private javax.swing.JTextField txtAutorEditar;
    private javax.swing.JTextField txtAñoEditar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JButton txtEditarLibro;
    private javax.swing.JTextField txtTituloEditar;
    // End of variables declaration//GEN-END:variables
}
