/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.app.poo.vista.libro;

import ec.edu.ups.app.poo.controlador.LibroControlador;
import ec.edu.ups.app.poo.modelo.Libro;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class VentanaBuscarLibro extends javax.swing.JInternalFrame {
     private LibroControlador libroControlador;
    /**
     * Creates new form VentanaBuscarLibro
     */
    public VentanaBuscarLibro(LibroControlador libroControlador) {
        initComponents();
        this.libroControlador = libroControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTituloBuscar = new javax.swing.JLabel();
        txtTituloBuscar = new javax.swing.JTextField();
        bnBuscarLibro = new javax.swing.JButton();
        lbDisponibleLibro = new javax.swing.JLabel();
        txtLibroDisponibleBuscar = new javax.swing.JTextField();
        generoLibro = new javax.swing.JLabel();
        txtLibroGeneroBuscar = new javax.swing.JTextField();
        lbAñoLibro = new javax.swing.JLabel();
        txtLibroAñoBuscar = new javax.swing.JTextField();
        lbAutorLibro = new javax.swing.JLabel();
        txtLibroAutorBuscar = new javax.swing.JTextField();
        lbCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Libro");

        jPanel1.setBackground(new java.awt.Color(114, 135, 174));

        lbTituloBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTituloBuscar.setText("Titulo");

        txtTituloBuscar.setEditable(false);

        bnBuscarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda-2.png"))); // NOI18N
        bnBuscarLibro.setText("Buscar");
        bnBuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnBuscarLibroActionPerformed(evt);
            }
        });

        lbDisponibleLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDisponibleLibro.setText("Disponible");

        txtLibroDisponibleBuscar.setEditable(false);
        txtLibroDisponibleBuscar.setBackground(new java.awt.Color(70, 73, 75));
        txtLibroDisponibleBuscar.setForeground(new java.awt.Color(255, 255, 255));

        generoLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        generoLibro.setText("Género");

        txtLibroGeneroBuscar.setEditable(false);
        txtLibroGeneroBuscar.setBackground(new java.awt.Color(70, 73, 75));
        txtLibroGeneroBuscar.setForeground(new java.awt.Color(255, 255, 255));

        lbAñoLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAñoLibro.setText("Año");

        txtLibroAñoBuscar.setEditable(false);
        txtLibroAñoBuscar.setBackground(new java.awt.Color(70, 73, 75));
        txtLibroAñoBuscar.setForeground(new java.awt.Color(255, 255, 255));

        lbAutorLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAutorLibro.setText("Autor");

        txtLibroAutorBuscar.setEditable(false);
        txtLibroAutorBuscar.setBackground(new java.awt.Color(70, 73, 75));
        txtLibroAutorBuscar.setForeground(new java.awt.Color(255, 255, 255));

        lbCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCodigo.setText("Codigo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTituloBuscar)
                    .addComponent(lbAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAñoLibro)
                    .addComponent(generoLibro)
                    .addComponent(lbDisponibleLibro)
                    .addComponent(lbCodigo))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLibroDisponibleBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLibroAutorBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLibroAñoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLibroGeneroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTituloBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addComponent(bnBuscarLibro)))
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnBuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTituloBuscar)
                    .addComponent(txtTituloBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAutorLibro)
                    .addComponent(txtLibroAutorBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAñoLibro)
                    .addComponent(txtLibroAñoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generoLibro)
                    .addComponent(txtLibroGeneroBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLibroDisponibleBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDisponibleLibro))
                .addGap(121, 121, 121))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnBuscarLibroActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(txtCodigo.getText()) ;
        
        Libro libro =  libroControlador.read(codigo);
        if (libro==null){
            JOptionPane.showMessageDialog(this, "El libro no existe!");
        }else{
        txtLibroAñoBuscar.setText(String.valueOf(libro.getAño()));
        txtLibroAutorBuscar.setText(libro.getAutor());
        txtTituloBuscar.setText(libro.getTitulo());
        txtLibroGeneroBuscar.setText(libro.getGenero());
        txtLibroDisponibleBuscar.setText(String.valueOf(libro.getDisponible()));
        }
        
    }//GEN-LAST:event_bnBuscarLibroActionPerformed

    public void cambiarIdioma(Locale locale) {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
        ResourceBundle titulos = ResourceBundle.getBundle("titulos.titulos", locale); 
            this.setTitle(titulos.getString("BuscarL"));
        lbTituloBuscar.setText(mensajes.getString("tituloLibro"));
        lbAutorLibro.setText(mensajes.getString("autorLibro"));
        lbAñoLibro.setText(mensajes.getString("anoLibro"));
        generoLibro.setText(mensajes.getString("Genero"));
        lbDisponibleLibro.setText(mensajes.getString("disponibleLibro"));
        bnBuscarLibro.setText(mensajes.getString("botonBuscar"));
         lbCodigo.setText(mensajes.getString("codigo"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnBuscarLibro;
    private javax.swing.JLabel generoLibro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAutorLibro;
    private javax.swing.JLabel lbAñoLibro;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbDisponibleLibro;
    private javax.swing.JLabel lbTituloBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtLibroAutorBuscar;
    private javax.swing.JTextField txtLibroAñoBuscar;
    private javax.swing.JTextField txtLibroDisponibleBuscar;
    private javax.swing.JTextField txtLibroGeneroBuscar;
    private javax.swing.JTextField txtTituloBuscar;
    // End of variables declaration//GEN-END:variables
}
