/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.app.poo.vista.prestamo;

import ec.edu.ups.app.poo.controlador.ClienteControlador;
import ec.edu.ups.app.poo.controlador.PrestamoControlador;
import ec.edu.ups.app.poo.modelo.Cliente;
import ec.edu.ups.app.poo.modelo.Libro;
import ec.edu.ups.app.poo.modelo.Prestamo;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class VentanaBuscarPrestamo extends javax.swing.JInternalFrame {
    private PrestamoControlador prestamoControlador;
    private ClienteControlador clienteControlador;
    /**
     * Creates new form VentanaBuscarPrestamo
     */
    public VentanaBuscarPrestamo(PrestamoControlador prestamoControlador,ClienteControlador clienteControlador) {
        initComponents();
        this.prestamoControlador = prestamoControlador;
        this.clienteControlador = clienteControlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        btBuscarPrestamo = new javax.swing.JButton();
        numCodigoPrestamo = new javax.swing.JLabel();
        txtNumCodigo = new javax.swing.JTextField();
        lbLibrosPrestados = new javax.swing.JLabel();
        lbIdentificacionPrestamo = new javax.swing.JLabel();
        txtIdentificacionPrestamo = new javax.swing.JTextField();
        lbFechaDevolucion = new javax.swing.JLabel();
        txtFechaDevolucion = new javax.swing.JTextField();
        fechaPrestamo = new javax.swing.JLabel();
        txtFechaPrestamo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbLibro = new javax.swing.JTable();
        lbNombreCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        lbCorreoCliente = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Prestamo");

        jPanel5.setBackground(new java.awt.Color(114, 135, 174));

        btBuscarPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btBuscarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda-2.png"))); // NOI18N
        btBuscarPrestamo.setText("Buscar");
        btBuscarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarPrestamoActionPerformed(evt);
            }
        });

        numCodigoPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numCodigoPrestamo.setText("Número de Prestamo");

        lbLibrosPrestados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbLibrosPrestados.setText("Libros");

        lbIdentificacionPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbIdentificacionPrestamo.setText("Identificación Cliente");

        txtIdentificacionPrestamo.setEditable(false);
        txtIdentificacionPrestamo.setBackground(new java.awt.Color(70, 73, 75));
        txtIdentificacionPrestamo.setForeground(new java.awt.Color(255, 255, 255));

        lbFechaDevolucion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbFechaDevolucion.setText("Fecha Devolución");

        txtFechaDevolucion.setEditable(false);
        txtFechaDevolucion.setBackground(new java.awt.Color(70, 73, 75));
        txtFechaDevolucion.setForeground(new java.awt.Color(255, 255, 255));

        fechaPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fechaPrestamo.setText("Fecha Prestamo");

        txtFechaPrestamo.setEditable(false);
        txtFechaPrestamo.setBackground(new java.awt.Color(70, 73, 75));
        txtFechaPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaPrestamoActionPerformed(evt);
            }
        });

        tbLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor", "Año", "Género", "Disponible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbLibro);

        lbNombreCliente.setText("Nombre");

        txtNombreCliente.setEditable(false);
        txtNombreCliente.setBackground(new java.awt.Color(70, 73, 75));
        txtNombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        lbCorreoCliente.setText("Correo");

        txtCorreo.setEditable(false);
        txtCorreo.setBackground(new java.awt.Color(70, 73, 75));
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(numCodigoPrestamo)
                                            .addComponent(lbIdentificacionPrestamo))
                                        .addGap(85, 85, 85))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fechaPrestamo)
                                            .addComponent(lbFechaDevolucion))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNumCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                        .addComponent(txtIdentificacionPrestamo)
                                        .addComponent(txtFechaDevolucion)))
                                .addGap(33, 33, 33)
                                .addComponent(btBuscarPrestamo))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCorreoCliente)
                                    .addComponent(lbNombreCliente))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(121, 121, 121))))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lbLibrosPrestados, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numCodigoPrestamo)
                    .addComponent(txtNumCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIdentificacionPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIdentificacionPrestamo))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNombreCliente)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCorreoCliente)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechaPrestamo)
                            .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFechaDevolucion)
                            .addComponent(txtFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(lbLibrosPrestados)
                        .addGap(51, 51, 51))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaPrestamoActionPerformed

    private void btBuscarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarPrestamoActionPerformed
        // TODO add your handling code here:
       int numPrestamo = Integer.parseInt(txtNumCodigo.getText());
       Prestamo prestamo = prestamoControlador.read(numPrestamo);
       if(prestamo!= null){
           SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");
           String fehchaP= fecha.format(prestamo.getFechaPrestamo());
           String fechaD = fecha.format(prestamo.getFechaDevolucion());
           txtFechaPrestamo.setText(fehchaP);
           txtFechaDevolucion.setText(fechaD);
           Cliente cliente = clienteControlador.read(prestamo.getIdentificacion());
           txtIdentificacionPrestamo.setText(cliente.getIdentificacion());
           txtNombreCliente.setText(cliente.getNombre());
           txtCorreo.setText(cliente.getCorreo());
           cargarDatos();
     
       }else{
           JOptionPane.showMessageDialog(this, "No existe el prestamo con tal numero");
       }
    }
    private void cargarDatos(){
        Prestamo prestamo = prestamoControlador.read(Integer.parseInt(txtNumCodigo.getText()));
        List<Libro> libros = prestamoControlador.listLibros(String.valueOf(prestamo.getNumeroPrestamo()));
        DefaultTableModel tabla = (DefaultTableModel) tbLibro.getModel();
        tabla.setNumRows(0);
        for(Libro libro: libros){
            Object[] rowData = {libro.getTitulo(),libro.getAutor(), libro.getAño(),libro.getGenero(), libro.getDisponible()};
            tabla.addRow(rowData);
        }
          
       
    }//GEN-LAST:event_btBuscarPrestamoActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    public void cambiarIdioma(Locale locale) {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
        ResourceBundle titulos = ResourceBundle.getBundle("titulos.titulos", locale); 
        ResourceBundle tablas = ResourceBundle.getBundle("tablas.tablas", locale); 
        String titulo = tablas.getString("tablaTitulo");
        String autor = tablas.getString("tablaAutor");
        String ano = tablas.getString("tablaAno");
        String genero = tablas.getString("tablaGenero");   
        String disponible = tablas.getString("tablaDisponible");               
        DefaultTableModel tabla = (DefaultTableModel) tbLibro.getModel();
        tabla.setColumnIdentifiers(new String [] {titulo, autor,ano,genero,disponible});
            this.setTitle(titulos.getString("BuscarP"));
        numCodigoPrestamo.setText(mensajes.getString("#Prestamo"));
        lbIdentificacionPrestamo.setText(mensajes.getString("idCliente"));
        lbNombreCliente.setText(mensajes.getString("nombre"));
        lbCorreoCliente.setText(mensajes.getString("correoCliente"));
        fechaPrestamo.setText(mensajes.getString("fechaPrestamo"));
        lbFechaDevolucion.setText(mensajes.getString("fechaDevolucion"));
        lbLibrosPrestados.setText(mensajes.getString("librosTxt"));
        btBuscarPrestamo.setText(mensajes.getString("buscarBibliotecaMenu"));        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarPrestamo;
    private javax.swing.JLabel fechaPrestamo;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbCorreoCliente;
    private javax.swing.JLabel lbFechaDevolucion;
    private javax.swing.JLabel lbIdentificacionPrestamo;
    private javax.swing.JLabel lbLibrosPrestados;
    private javax.swing.JLabel lbNombreCliente;
    private javax.swing.JLabel numCodigoPrestamo;
    private javax.swing.JTable tbLibro;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFechaDevolucion;
    private javax.swing.JTextField txtFechaPrestamo;
    private javax.swing.JTextField txtIdentificacionPrestamo;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNumCodigo;
    // End of variables declaration//GEN-END:variables
}
