/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.app.poo.vista.prestamo;

import ec.edu.ups.app.poo.IDAO.LibroIDAO;
import ec.edu.ups.app.poo.controlador.BibliotecaControlador;
import ec.edu.ups.app.poo.controlador.ClienteControlador;
import ec.edu.ups.app.poo.controlador.LibroControlador;
import ec.edu.ups.app.poo.controlador.PrestamoControlador;
import ec.edu.ups.app.poo.modelo.Biblioteca;
import ec.edu.ups.app.poo.modelo.Cliente;
import ec.edu.ups.app.poo.modelo.Libro;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class VentanaCrearPrestamo extends javax.swing.JInternalFrame {
    private PrestamoControlador prestamoControlador;
    private BibliotecaControlador bibliotecaControlador;
    private ClienteControlador clientecontrolador;
    private LibroControlador libroControlador;
    
    
    
   
    /**
     * Creates new form VentanaCrearPrestamo
     */
    public VentanaCrearPrestamo(PrestamoControlador prestamoControlador,BibliotecaControlador bibliotecaControlador,ClienteControlador clientecontrolador, LibroControlador libroControlador) {
        initComponents();
        this.prestamoControlador = prestamoControlador;
        this.bibliotecaControlador = bibliotecaControlador;
        this.clientecontrolador = clientecontrolador;
        this.libroControlador = libroControlador;
        bibliotecas();
        libros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        numCodigoPrestamo = new javax.swing.JLabel();
        lbIdentificacionPrestamo = new javax.swing.JLabel();
        lbFechaDevolucion = new javax.swing.JLabel();
        txtNumCodigo = new javax.swing.JTextField();
        txtIdentificacion = new javax.swing.JTextField();
        txtFechaDevolucion = new javax.swing.JTextField();
        btGuardarPrestamo = new javax.swing.JButton();
        bibliotecaTxt = new javax.swing.JLabel();
        bibliotecaBox = new javax.swing.JComboBox<>();
        libroTxt = new javax.swing.JLabel();
        libroBox = new javax.swing.JComboBox<>();
        btnBuscarCliente = new javax.swing.JButton();
        lbNombreCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        lbCorreoCliente = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btActualizar = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Crear Prestamo");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(195, 172, 133));

        numCodigoPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numCodigoPrestamo.setText("Número de Prestamo");

        lbIdentificacionPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbIdentificacionPrestamo.setText("Identificación Cliente");

        lbFechaDevolucion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbFechaDevolucion.setText("Fecha Devolución");

        btGuardarPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btGuardarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btGuardarPrestamo.setText("Guardar");
        btGuardarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarPrestamoActionPerformed(evt);
            }
        });

        bibliotecaTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bibliotecaTxt.setText("Biblioteca");

        bibliotecaBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bibliotecaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bibliotecaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bibliotecaBoxActionPerformed(evt);
            }
        });

        libroTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        libroTxt.setText("Libros");

        libroBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        libroBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libroBoxActionPerformed(evt);
            }
        });

        btnBuscarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda-2.png"))); // NOI18N
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        lbNombreCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNombreCliente.setText("Nombre");

        txtNombreCliente.setEditable(false);
        txtNombreCliente.setBackground(new java.awt.Color(70, 73, 75));
        txtNombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        lbCorreoCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCorreoCliente.setText("Correo");

        txtCorreo.setEditable(false);
        txtCorreo.setBackground(new java.awt.Color(70, 73, 75));
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));

        btActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        btActualizar.setText("Actualizar");
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(numCodigoPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(txtNumCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bibliotecaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(libroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(libroBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bibliotecaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCorreoCliente)
                                    .addComponent(lbNombreCliente))
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCorreo)
                                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbIdentificacionPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarCliente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btGuardarPrestamo)
                .addGap(251, 251, 251))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numCodigoPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btActualizar)
                    .addComponent(bibliotecaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bibliotecaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(libroBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIdentificacionPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreCliente)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCorreoCliente)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFechaDevolucion))
                .addGap(38, 38, 38)
                .addComponent(btGuardarPrestamo)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarPrestamoActionPerformed
        int numPrestamo = Integer.parseInt(txtNumCodigo.getText());
        if(prestamoControlador.read(numPrestamo)== null){
            String identificacion = txtIdentificacion.getText();
            Date fechaPrestamo = new Date();
            SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");
            Date fechaDevolucion= null;
            if(validarFecha(txtFechaDevolucion.getText())){
            try {
                fechaDevolucion = fecha.parse(txtFechaDevolucion.getText());
            } catch (ParseException ex) {
                Logger.getLogger(VentanaCrearPrestamo.class.getName()).log(Level.SEVERE, null, ex);
            }
            prestamoControlador.create(numPrestamo, fechaPrestamo, fechaDevolucion, identificacion );
           if(prestamoControlador.agregarCliente(identificacion)==false) {
               JOptionPane.showMessageDialog(this, "El cliente no existe");
           }else{
               prestamoControlador.agregarLibros(String.valueOf(numPrestamo), String.valueOf(libroBox.getSelectedItem()));
                Libro libro =  libroControlador.read(String.valueOf(libroBox.getSelectedItem()));
            libroControlador.update(libro.getCodigo(), libro.getTitulo(), libro.getAutor(), libro.getAño(), libro.getGenero(), "NO", libro.getNombiblioteca());
            JOptionPane.showMessageDialog(this, "Se guardo correctamente!");
           }
            }else{
                   JOptionPane.showMessageDialog(this, "Ingrese una fecha correcta!");
                   }
          }else{
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error!");
        
        }
    }//GEN-LAST:event_btGuardarPrestamoActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        String identificacion = txtIdentificacion.getText();
        Cliente cliente = clientecontrolador.read(identificacion);
        if (cliente==null){
            JOptionPane.showMessageDialog(this, "El cliente no existe!");
        }else{
            txtIdentificacion.setText(cliente.getIdentificacion());
            txtNombreCliente.setText(cliente.getNombre());
            txtCorreo.setText(cliente.getCorreo());

        }
    }
         public static boolean validarFecha(String fechaIngresada) {
        // Obtener la fecha actual
        LocalDate fechaActual = LocalDate.now();

        // Convertir la fecha ingresada a un objeto LocalDate
        LocalDate fechaIngresadaObj = LocalDate.parse(fechaIngresada, DateTimeFormatter.ofPattern("dd/MM/yyyy"));

        // Comparar las fechas
        if (fechaIngresadaObj.isBefore(fechaActual)) {
            return false; // La fecha ingresada es anterior a la fecha actual
        } else {
            return true; // La fecha ingresada es válida
        }
    

    
        
        
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void bibliotecaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bibliotecaBoxActionPerformed
        // TODO add your handling code here:
    }
    public void bibliotecas(){
        bibliotecaBox.removeAllItems();
    List<Biblioteca> bibliotecas = bibliotecaControlador.list();
    for (Biblioteca biblioteca : bibliotecas) {
        bibliotecaBox.addItem(biblioteca.getNombre());
    }
    }
    public void libros(){
        libroBox.removeAllItems();
        String nombre = String.valueOf(bibliotecaBox.getSelectedItem());
        Biblioteca biblioteca= bibliotecaControlador.read( nombre);
        List<Libro> libros = bibliotecaControlador.listLibros(biblioteca.getNombre());
        for(Libro libro : libros){
            libroBox.addItem(libro.getTitulo());
        }
   
    
    }//GEN-LAST:event_bibliotecaBoxActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        // TODO add your handling code here:
        libros();
    }//GEN-LAST:event_btActualizarActionPerformed

    private void libroBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libroBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libroBoxActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        libros();
    }//GEN-LAST:event_formInternalFrameActivated

    public void cambiarIdioma(Locale locale) {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
        ResourceBundle titulos = ResourceBundle.getBundle("titulos.titulos", locale); 
            this.setTitle(titulos.getString("BuscarP"));
        numCodigoPrestamo.setText(mensajes.getString("#Prestamo"));
        libroTxt.setText(mensajes.getString("libroMenu"));
        bibliotecaTxt.setText(mensajes.getString("bibliotecaMenu"));  
        lbIdentificacionPrestamo.setText(mensajes.getString("idCliente"));        
        lbNombreCliente.setText(mensajes.getString("nombre"));
        lbCorreoCliente.setText(mensajes.getString("correoCliente"));
        lbFechaDevolucion.setText(mensajes.getString("fechaDevolucion"));
        btActualizar.setText(mensajes.getString("botonActualizar"));
        btnBuscarCliente.setText(mensajes.getString("botonBuscar"));
        btGuardarPrestamo.setText(mensajes.getString("botonGuardar"));        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bibliotecaBox;
    private javax.swing.JLabel bibliotecaTxt;
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btGuardarPrestamo;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCorreoCliente;
    private javax.swing.JLabel lbFechaDevolucion;
    private javax.swing.JLabel lbIdentificacionPrestamo;
    private javax.swing.JLabel lbNombreCliente;
    private javax.swing.JComboBox<String> libroBox;
    private javax.swing.JLabel libroTxt;
    private javax.swing.JLabel numCodigoPrestamo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFechaDevolucion;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNumCodigo;
    // End of variables declaration//GEN-END:variables
}
