/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.app.poo.vista.prestamo;

import ec.edu.ups.app.poo.controlador.BibliotecaControlador;
import ec.edu.ups.app.poo.controlador.ClienteControlador;
import ec.edu.ups.app.poo.controlador.LibroControlador;
import ec.edu.ups.app.poo.controlador.PrestamoControlador;
import ec.edu.ups.app.poo.modelo.Biblioteca;
import ec.edu.ups.app.poo.modelo.Cliente;
import ec.edu.ups.app.poo.modelo.Libro;
import ec.edu.ups.app.poo.modelo.Prestamo;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class VentanaEditarPrestamo extends javax.swing.JInternalFrame {
    private PrestamoControlador prestamoControlador;
    private BibliotecaControlador bibliotecaControlador;
    private ClienteControlador clientecontrolador; 
    private LibroControlador libroControlador;
    private DefaultTableModel tabla;
    /**
     * Creates new form VentanaEditarPrestamo
     */
    public VentanaEditarPrestamo(PrestamoControlador prestamoControlador,BibliotecaControlador bibliotecaControlador,ClienteControlador clientecontrolador,LibroControlador libroControlador) {
        initComponents();
        this.prestamoControlador = prestamoControlador;
        this.clientecontrolador = clientecontrolador;
        this.bibliotecaControlador = bibliotecaControlador;
        this.libroControlador = libroControlador;
        bibliotecas();
        libros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numCodigoPrestamo = new javax.swing.JLabel();
        lbLibrosPrestados = new javax.swing.JLabel();
        lbIdentificacionPrestamo = new javax.swing.JLabel();
        lbFechaDevolucion = new javax.swing.JLabel();
        txtNumCodigo = new javax.swing.JTextField();
        txtNumLibros = new javax.swing.JTextField();
        txtIdentificacionPrestamo = new javax.swing.JTextField();
        txtFechaDevolucion = new javax.swing.JTextField();
        btGuardarPrestamo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        numCodigoPrestamo2 = new javax.swing.JLabel();
        lbIdentificacionPrestamo2 = new javax.swing.JLabel();
        lbFechaDevolucion2 = new javax.swing.JLabel();
        txtNumPrestamo = new javax.swing.JTextField();
        txtIdentificacion = new javax.swing.JTextField();
        txtFechaDevolucion1 = new javax.swing.JTextField();
        btEditarPrestamo1 = new javax.swing.JButton();
        bibliotecaTxt = new javax.swing.JLabel();
        bibliotecaBox = new javax.swing.JComboBox<>();
        librosTxt = new javax.swing.JLabel();
        libroBox = new javax.swing.JComboBox<>();
        btnBuscarCliente = new javax.swing.JButton();
        lbNombreCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        lbCorreoCliente = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btActualizar = new javax.swing.JButton();
        btBuscarPrestamo = new javax.swing.JButton();
        lbLibrosPrestados1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbLibro = new javax.swing.JTable();
        btLimpiar = new javax.swing.JButton();
        txtDevolverLibro = new javax.swing.JTextField();
        btDevolver = new javax.swing.JButton();
        btAgregar = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Datos"));

        numCodigoPrestamo.setText("Número Código");

        lbLibrosPrestados.setText("Numero Libros");

        lbIdentificacionPrestamo.setText("Identificación");

        lbFechaDevolucion.setText("Fecha Devolución");

        btGuardarPrestamo.setText("Guardar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numCodigoPrestamo)
                            .addComponent(lbLibrosPrestados)
                            .addComponent(lbIdentificacionPrestamo)
                            .addComponent(lbFechaDevolucion))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumCodigo)
                            .addComponent(txtNumLibros)
                            .addComponent(txtIdentificacionPrestamo)
                            .addComponent(txtFechaDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btGuardarPrestamo)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numCodigoPrestamo)
                    .addComponent(txtNumCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLibrosPrestados)
                    .addComponent(txtNumLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdentificacionPrestamo)
                    .addComponent(txtIdentificacionPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFechaDevolucion)
                    .addComponent(txtFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btGuardarPrestamo)
                .addGap(28, 28, 28))
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Editar Prestamo");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel3.setBackground(new java.awt.Color(160, 177, 132));

        numCodigoPrestamo2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numCodigoPrestamo2.setText("Número de Prestamo");

        lbIdentificacionPrestamo2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbIdentificacionPrestamo2.setText("Identificación Cliente");

        lbFechaDevolucion2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbFechaDevolucion2.setText("Fecha Devolución");

        txtIdentificacion.setEditable(false);
        txtIdentificacion.setBackground(new java.awt.Color(70, 73, 75));
        txtIdentificacion.setForeground(new java.awt.Color(255, 255, 255));

        txtFechaDevolucion1.setEditable(false);
        txtFechaDevolucion1.setBackground(new java.awt.Color(70, 73, 75));
        txtFechaDevolucion1.setForeground(new java.awt.Color(255, 255, 255));

        btEditarPrestamo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btEditarPrestamo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        btEditarPrestamo1.setText("Editar");
        btEditarPrestamo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarPrestamo1ActionPerformed(evt);
            }
        });

        bibliotecaTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bibliotecaTxt.setText("Biblioteca");

        bibliotecaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bibliotecaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bibliotecaBoxActionPerformed(evt);
            }
        });

        librosTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        librosTxt.setText("Libros");

        libroBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBuscarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda-2.png"))); // NOI18N
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        lbNombreCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNombreCliente.setText("Nombre");

        txtNombreCliente.setEditable(false);
        txtNombreCliente.setBackground(new java.awt.Color(70, 73, 75));
        txtNombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        lbCorreoCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCorreoCliente.setText("Correo");

        txtCorreo.setEditable(false);
        txtCorreo.setBackground(new java.awt.Color(70, 73, 75));
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));

        btActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        btActualizar.setText("Actualizar");
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        btBuscarPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btBuscarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda.png"))); // NOI18N
        btBuscarPrestamo.setText(" Buscar");
        btBuscarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarPrestamoActionPerformed(evt);
            }
        });

        lbLibrosPrestados1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbLibrosPrestados1.setText("Libros");

        tbLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor", "Año", "Género", "Disponible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbLibro);

        btLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/escoba.png"))); // NOI18N
        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        txtDevolverLibro.setText("Ingrese el titulo");
        txtDevolverLibro.setToolTipText("Ingrese el titulo de libro");
        txtDevolverLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDevolverLibroActionPerformed(evt);
            }
        });

        btDevolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        btDevolver.setText("Devolver");
        btDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDevolverActionPerformed(evt);
            }
        });

        btAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mas.png"))); // NOI18N
        btAgregar.setText(" Agregar");
        btAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btDevolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDevolverLibro))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLibrosPrestados1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(lbFechaDevolucion2))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(bibliotecaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(numCodigoPrestamo2)
                                            .addComponent(librosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(lbIdentificacionPrestamo2))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(lbNombreCliente)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtNumPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(bibliotecaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(libroBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(43, 43, 43)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btActualizar)
                                                    .addComponent(btBuscarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(lbCorreoCliente)
                                                .addGap(36, 36, 36)
                                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFechaDevolucion1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnBuscarCliente)))))))
                        .addContainerGap(64, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(btEditarPrestamo1)
                .addGap(76, 76, 76)
                .addComponent(btLimpiar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numCodigoPrestamo2)
                    .addComponent(txtNumPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarPrestamo))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bibliotecaTxt)
                    .addComponent(bibliotecaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btActualizar))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(librosTxt)
                    .addComponent(libroBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdentificacionPrestamo2)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNombreCliente)
                    .addComponent(lbCorreoCliente)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaDevolucion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFechaDevolucion2))
                .addGap(18, 18, 18)
                .addComponent(lbLibrosPrestados1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtDevolverLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btDevolver))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btEditarPrestamo1)
                            .addComponent(btLimpiar))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEditarPrestamo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarPrestamo1ActionPerformed
        int numPrestamo = Integer.parseInt(txtNumPrestamo.getText());
        Prestamo prestamo = prestamoControlador.read(numPrestamo);
        if(prestamo!= null){
            String identificacion = txtIdentificacion.getText();

            SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");
            Date fechaDevolucion = null;
            if(validarFecha(txtFechaDevolucion1.getText())){
            try {
               fechaDevolucion = fecha.parse(txtFechaDevolucion1.getText());
            } catch (ParseException ex) {
                Logger.getLogger(VentanaCrearPrestamo.class.getName()).log(Level.SEVERE, null, ex);
            }
            prestamoControlador.update(numPrestamo,prestamo.getFechaPrestamo(),fechaDevolucion, txtIdentificacion.getText());
            
            if(prestamoControlador.agregarCliente(identificacion)==false) {
                
                
                JOptionPane.showMessageDialog(this, "El cliente no existe");
            }else{
                Cliente cliente = clientecontrolador.read(identificacion);
                prestamo.setCliente(cliente);
                JOptionPane.showMessageDialog(this, "Se edito correctamente!");
                btLimpiarActionPerformed(evt);
                
            }
            }else{
                JOptionPane.showMessageDialog(this, "Ingrese una fecha correcta!");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error!");

        }
    }//GEN-LAST:event_btEditarPrestamo1ActionPerformed

    private void bibliotecaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bibliotecaBoxActionPerformed
        // TODO add your handling code here:
        }
        public void bibliotecas(){
            bibliotecaBox.removeAllItems();
            List<Biblioteca> bibliotecas = bibliotecaControlador.list();
            for (Biblioteca biblioteca : bibliotecas) {
                bibliotecaBox.addItem(biblioteca.getNombre());
            }
        }
        public void libros(){
            libroBox.removeAllItems();
            String nombre = String.valueOf(bibliotecaBox.getSelectedItem());
            Biblioteca biblioteca= bibliotecaControlador.read( nombre);
            List<Libro> libros = bibliotecaControlador.listLibros(nombre);
            for(Libro libro : libros){
                libroBox.addItem(libro.getTitulo());
            }
        }
      public static boolean validarFecha(String fechaIngresada) {
        // Obtener la fecha actual
        LocalDate fechaActual = LocalDate.now();

        // Convertir la fecha ingresada a un objeto LocalDate
        LocalDate fechaIngresadaObj = LocalDate.parse(fechaIngresada, DateTimeFormatter.ofPattern("dd/MM/yyyy"));

        // Comparar las fechas
        if (fechaIngresadaObj.isBefore(fechaActual)) {
            return false; // La fecha ingresada es anterior a la fecha actual
        } else {
            return true; // La fecha ingresada es válida
        }
    

    

    }//GEN-LAST:event_bibliotecaBoxActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        String identificacion = txtIdentificacion.getText();
        Cliente cliente = clientecontrolador.read(identificacion);
        if (cliente==null){
            JOptionPane.showMessageDialog(this, "El cliente no existe!");
        }else{
            txtIdentificacion.setText(cliente.getIdentificacion());
            txtNombreCliente.setText(cliente.getNombre());
            txtCorreo.setText(cliente.getCorreo());
            
        }
    }
    private void cargarDatos() {
        Prestamo prestamo = prestamoControlador.read(Integer.parseInt(txtNumPrestamo.getText()));
        List<Libro> libros = prestamoControlador.listLibros(String.valueOf(prestamo.getNumeroPrestamo()));
         tabla = (DefaultTableModel) tbLibro.getModel();
        tabla.setNumRows(0);
        for (Libro libro : libros) {
            Object[] rowData = {libro.getTitulo(), libro.getAutor(), libro.getAño(), libro.getGenero(), libro.getDisponible()};
            tabla.addRow(rowData);
        }

     

    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        // TODO add your handling code here:
        libros();
    }//GEN-LAST:event_btActualizarActionPerformed

    private void btBuscarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarPrestamoActionPerformed
        // TODO add your handling code here:
        Prestamo prestamo = prestamoControlador.read(Integer.parseInt(txtNumPrestamo.getText()));
        if(prestamo!=null){
            SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");
            String fechaD = fecha.format(prestamo.getFechaDevolucion());
        txtNumPrestamo.setText(String.valueOf(prestamo.getNumeroPrestamo()));
        Cliente cliente = clientecontrolador.read(prestamo.getIdentificacion());
        txtIdentificacion.setText(cliente.getIdentificacion());
        txtNombreCliente.setText(cliente.getNombre()); 
        txtCorreo.setText(cliente.getCorreo());
        txtFechaDevolucion1.setText(fechaD); 
        txtNumPrestamo.setEditable(false);
        txtIdentificacion.setEditable(true);
        txtNombreCliente.setEditable(true);
        txtCorreo.setEditable(true);
        txtFechaDevolucion1.setEditable(true);
        txtDevolverLibro.setEditable(true); 
        cargarDatos();
        }else{
            JOptionPane.showMessageDialog(this, "El prestamo no existe!");
        }
        
    }//GEN-LAST:event_btBuscarPrestamoActionPerformed

    private void txtDevolverLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDevolverLibroActionPerformed
        // TODO add your handling code here:
       prestamoControlador.agregarLibros(String.valueOf(txtNumPrestamo.getText()), String.valueOf(libroBox.getSelectedItem()));
    }//GEN-LAST:event_txtDevolverLibroActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        // TODO add your handling code here:
        txtNumPrestamo.setText("");
        txtNumPrestamo.setEditable(true);
        txtIdentificacion.setText("");
        txtIdentificacion.setEditable(false);
        txtNombreCliente.setText(""); 
        txtNombreCliente.setEditable(false);
        txtCorreo.setText("");
        txtCorreo.setEditable(false);
        txtFechaDevolucion1.setText("");
        txtFechaDevolucion1.setEditable(false);
        txtDevolverLibro.setText("");
        txtDevolverLibro.setEditable(false);
        tabla.setNumRows(0);
        
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void btDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDevolverActionPerformed
        // TODO add your handling code here:
        if(prestamoControlador.devolverLibro(txtDevolverLibro.getText(), txtNumPrestamo.getText())){
            
           Libro libro =  libroControlador.read(txtDevolverLibro.getText());
          
           prestamoControlador.actualizarLibro(txtNumPrestamo.getText(), libro.getTitulo(), libro);
           libroControlador.update(libro.getCodigo(), libro.getTitulo(), libro.getAutor(), libro.getAño(), libro.getGenero(), "SI", libro.getNombiblioteca());
           cargarDatos();
         JOptionPane.showMessageDialog(this, "Se ha devuelto correctamente!");
        }else{
            JOptionPane.showMessageDialog(this, "Se ha producido un error!");    
        }
    }//GEN-LAST:event_btDevolverActionPerformed

    private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarActionPerformed
        // TODO add your handling code here:
        
        if(prestamoControlador.agregarLibros(String.valueOf(txtNumPrestamo.getText()), String.valueOf(libroBox.getSelectedItem()))){
           Libro libro =  libroControlador.read(String.valueOf(libroBox.getSelectedItem()));
            libroControlador.update(libro.getCodigo(), libro.getTitulo(), libro.getAutor(), libro.getAño(), libro.getGenero(), "NO", libro.getNombiblioteca());
            JOptionPane.showMessageDialog(this, "Se agregó correctamente!");
        }else{
            JOptionPane.showMessageDialog(this, "Se ha producido un error!");
            
        }
        
    }//GEN-LAST:event_btAgregarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        bibliotecas();
        libros();
    }//GEN-LAST:event_formInternalFrameActivated

    public void cambiarIdioma(Locale locale) {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
        ResourceBundle titulos = ResourceBundle.getBundle("titulos.titulos", locale); 
        this.setTitle(titulos.getString("EditarP"));
        ResourceBundle tablas = ResourceBundle.getBundle("tablas.tablas", locale); 
        String titulo = tablas.getString("tablaTitulo");
        String autor = tablas.getString("tablaAutor");
        String ano = tablas.getString("tablaAno");
        String genero = tablas.getString("tablaGenero");   
        String disponible = tablas.getString("tablaDisponible");               
        DefaultTableModel tabla1 = (DefaultTableModel) tbLibro.getModel();
        tabla1.setColumnIdentifiers(new String [] {titulo, autor,ano,genero,disponible});
        numCodigoPrestamo.setText(mensajes.getString("#Prestamo"));
        lbIdentificacionPrestamo.setText(mensajes.getString("idCliente"));
        lbNombreCliente.setText(mensajes.getString("nombre"));
        lbCorreoCliente.setText(mensajes.getString("correoCliente"));
        bibliotecaTxt.setText(mensajes.getString("bibliotecaMenu"));
        librosTxt.setText(mensajes.getString("libroMenu"));
        lbFechaDevolucion.setText(mensajes.getString("fechaDevolucion"));
        lbLibrosPrestados1.setText(mensajes.getString("librosTxt"));
        btActualizar.setText(mensajes.getString("botonActualizar")); 
        btBuscarPrestamo.setText(mensajes.getString("botonBuscar"));
        btnBuscarCliente.setText(mensajes.getString("botonBuscar"));
        btGuardarPrestamo.setText(mensajes.getString("botonGuardar"));    
        btDevolver.setText(mensajes.getString("botonDevolver"));
        btEditarPrestamo1.setText(mensajes.getString("botonEditar"));
        btLimpiar.setText(mensajes.getString("botonLimpiar"));        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bibliotecaBox;
    private javax.swing.JLabel bibliotecaTxt;
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btAgregar;
    private javax.swing.JButton btBuscarPrestamo;
    private javax.swing.JButton btDevolver;
    private javax.swing.JButton btEditarPrestamo1;
    private javax.swing.JButton btGuardarPrestamo;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCorreoCliente;
    private javax.swing.JLabel lbFechaDevolucion;
    private javax.swing.JLabel lbFechaDevolucion2;
    private javax.swing.JLabel lbIdentificacionPrestamo;
    private javax.swing.JLabel lbIdentificacionPrestamo2;
    private javax.swing.JLabel lbLibrosPrestados;
    private javax.swing.JLabel lbLibrosPrestados1;
    private javax.swing.JLabel lbNombreCliente;
    private javax.swing.JComboBox<String> libroBox;
    private javax.swing.JLabel librosTxt;
    private javax.swing.JLabel numCodigoPrestamo;
    private javax.swing.JLabel numCodigoPrestamo2;
    private javax.swing.JTable tbLibro;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDevolverLibro;
    private javax.swing.JTextField txtFechaDevolucion;
    private javax.swing.JTextField txtFechaDevolucion1;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtIdentificacionPrestamo;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNumCodigo;
    private javax.swing.JTextField txtNumLibros;
    private javax.swing.JTextField txtNumPrestamo;
    // End of variables declaration//GEN-END:variables
}
